<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%@ taglib uri="http://sakaiproject.org/jsf/syllabus" prefix="syllabus" %>
<% response.setContentType("text/html; charset=UTF-8"); %>

<f:view>

<jsp:useBean id="msgs" class="org.sakaiproject.util.ResourceLoader" scope="session">
   <jsp:setProperty name="msgs" property="baseName" value="org.sakaiproject.tool.syllabus.bundle.Messages"/>
</jsp:useBean>

	<sakai:view_container title="#{msgs.title_list}">
	<sakai:view_content>
<style type="text/css">
.col80 {width:80%;}
.col20 {width:20%;text-align:center;}
.col100 {width:100%;text-align:center;}
.agreeTableCollapseWithBorder {
      border: 2px double #9DA2A6;
 	  background-color: #FFFFCB;
}
.centered {align:center;}
</style>
<script language="JavaScript">
	// if redirected, just open in another window else
	// open with size approx what actual print out will look like
	function printFriendly(url) {

			window.open(url,"mywindow","width=960,height=1100,scrollbars=yes"); 
		
	}
	
	function OpenPMWindow(url, name) {
			var pmWindow = window.open(url,name,"status=no, menubar=no, location=no,scrollbars=yes,width=960,height=1100");	
			if (window.focus) { pmWindow.focus(); } ; 	
	}
</script>

<%-- gsilver: global things about syllabus tool:
1 ) what happens to empty lists - still generate a table?
2 ) Ids generated by jsf start with _  not optimal keeps us from validating fully.
 --%>
	<h:form id="syllabus">
		<%--gsilver: would be best if used all sakai tags, or none, 2 blocks
		following just gets tries to get around the mix --%>		
				 	<sakai:tool_bar>
						<syllabus:syllabus_ifnot test="#{SyllabusTool.editAble}">
						<h:graphicImage url="/images/preview.png" alt="" title=""height="16" width="16"  style="border:0;margin-right:3px;"/>
	  					<h:outputText  value="#{msgs.bar_student_view}"/>
						<sakai:tool_bar_spacer/>
						  	<%-- (gsilver) cannot pass a needed title atribute to this next item --%>
						  	<h:commandLink styleClass="toolUiLink" id="createEditAction" action="#{SyllabusTool.processCreateAndEdit}" immediate="true">
		   					<h:graphicImage url="/images/document_edit.gif" alt="" title="" height="16" width="16" style="border:0;margin-right:3px;" />
	  					     <h:outputText  value="#{msgs.bar_create_edit}"/>
						   </h:commandLink>
					</syllabus:syllabus_ifnot>
			</sakai:tool_bar>
			<br />
			<syllabus:syllabus_if test="#{SyllabusTool.mapBlocked}">
				<h:outputText value="#{SyllabusTool.displayBlockMsg}" escape="false" styleClass="alertMessage" rendered="#{SyllabusTool.displayBlockMsg != null}"/>			
	
				<h:panelGrid width="100%" columnClasses="col80,col20" columns="2">
					<h:column/>
					<h:column>										
						<h:outputLink id="print" value="javascript:printFriendly('#{SyllabusTool.printFriendlyUrl}');" styleClass="toolUiLink">
							<h:graphicImage url="/images/printer.png" alt="" title="" style="border:0;margin-right:3px;"/>
							<h:outputText value="#{msgs.bar_print}" />	
						</h:outputLink>	
						</h:column>
				</h:panelGrid>
				<syllabus:syllabus_if test="#{SyllabusTool.syllabusItem.redirectURL}">
				<h:dataTable value="#{SyllabusTool.entries}" var="eachEntry" rendered="#{! SyllabusTool.syllabusItem.redirectURL}" width="100%" style="margin-top:1em;clear:both;" summary="#{msgs.mainCaption}" >
					<h:column>
							<f:verbatim><h4 class="textPanelHeader"></f:verbatim>		  
								<h:outputText value="#{eachEntry.entry.title}" />
							<f:verbatim></h4></f:verbatim>
							<f:verbatim><div class="textPanel"></f:verbatim>
							<syllabus:syllabus_htmlShowArea value="#{eachEntry.cleanAsset}" />
							<f:verbatim></div></f:verbatim>
							<h:dataTable value="#{eachEntry.attachmentList}" var="eachAttach" styleClass="indnt1" summary="layout">
							  <h:column>
									<f:facet name="header">
										<h:outputText value="" />
									</f:facet>
									<sakai:contentTypeMap fileType="#{eachAttach.type}" mapType="image" var="imagePath" pathPrefix="/library/image/"/>									
									<h:graphicImage id="exampleFileIcon" value="#{imagePath}" />	
									<h:outputLink value="#{eachAttach.theUrl}" target="_blank" title="#{msgs.openLinkNewWindow}">
										<h:outputText value=" "/><h:outputText value="#{eachAttach.name}"/>
									</h:outputLink>
								</h:column>
							</h:dataTable>
					</h:column>
				</h:dataTable>
				<h:outputText value="#{msgs.syllabus_noEntry}" styleClass="instruction" rendered="#{SyllabusTool.displayNoEntryMsg}"/>
			</syllabus:syllabus_if>		
			
			<!-- render redirect url in iframe if setting is not to open in new window -->			
			<h:outputText value="#{msgs.syllabus_url_alert}" rendered="#{SyllabusTool.editAble == 'true' && SyllabusTool.redirectUrlHttpsPrefix != null && !SyllabusTool.redirectUrlHttpsPrefix && !SyllabusTool.syllabusItem.openNewWindow}" styleClass="alertMessage" />		
			<syllabus:syllabus_ifnot test="#{SyllabusTool.testOpenWindow}">						  
  				<syllabus:syllabus_iframe redirectUrl="#{SyllabusTool.syllabusItem.redirectURL}" width="100%" height="500"/>
  			</syllabus:syllabus_ifnot>	 		
  			
  		  	<!--  render redirect url as anchor tag if open in new window is checked -->
  			<h:outputText value="<br/>" escape="false" rendered="#{SyllabusTool.redirectUrlHttpsPrefix != null && !SyllabusTool.redirectUrlHttpsPrefix}"/>
  			<h:outputText value="Please review the " rendered="#{SyllabusTool.syllabusItem.openNewWindow && SyllabusTool.redirectViewURL != ''}"/>
  			<h:outputLink value="#{SyllabusTool.redirectViewURL}" target="_blank" styleClass="toolUiLinkU" rendered="#{SyllabusTool.syllabusItem.openNewWindow && SyllabusTool.redirectViewURL != ''}" >
					<h:outputText value="course syllabus." />	
			</h:outputLink>	
  					
		  <h:outputText value="#{SyllabusTool.viewDate}" style="visibility:hidden;display:none;"/>	
		</syllabus:syllabus_if>	
			<%--agreement box --%>
				<syllabus:syllabus_ifnot test="#{SyllabusTool.syllabusItem.redirectURL}">
					<h:outputText value="<br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/>" escape="false" />
				</syllabus:syllabus_ifnot>
			<div align="center">
						<h:panelGrid width="60%" cellspacing="1" cellpadding="5" columnClasses="col100" columns="1" styleClass="agreeTableCollapseWithBorder" rendered="#{SyllabusTool.renderAgreementBox}">
								<h:column/>
								<h:column>
									<h:outputText value="#{msgs.syllabus_agree_header1}" style="font-style:italic;font-weight:bold;"/> 
								</h:column>	
								<h:column>
									<h:commandButton id="agreeButton" immediate="true" action="#{SyllabusTool.agree}" value="#{msgs.syllabus_agree}" accesskey="#{msgs.agree_access}" 
									style="padding-left:2em;background: #eee url('images/correct.png') .2em no-repeat;"
									title="#{msgs.syllabus_agree_text}" /> 
								</h:column>
								<h:column/>
						</h:panelGrid>		
			</div>			
	
			<syllabus:syllabus_ifnot test="#{SyllabusTool.mapBlocked}">
				<h:outputText value="#{SyllabusTool.displayBlockMsg}" escape="FALSE" styleClass="alertMessage"/>		
			</syllabus:syllabus_ifnot>			
		</h:form>
	</sakai:view_content>
	</sakai:view_container>
</f:view>
